//! Shared code for the neural teleport range-check and one-hot proofs.
//!
//! This module contains shared logic for proving and verifying the combined range-check and one-hot checks
//! used in the neural teleport operator. It defines:
//! 1. The `NeuralTeleportRangeOneHot` trait, which specifies operator-specific hooks
//!    required by the shared proof flow, such as RA one-hot encoding descriptors and lookup index generation.
//! 2. The `prove_range_and_onehot` function, which implements the combined proof flow for both the teleport
//!    range-check and operator-specific RA one-hot checks, as well as the consistency check between them.
//! 3. The `verify_range_and_onehot` function, which verifies the proofs generated by `prove_range_and_onehot`.
use crate::onnx_proof::{
    range_checking::{
        range_check_operands::TeleportRangeCheckOperands, RangeCheckEncoding, RangeCheckProvider,
    },
    ProofId, ProofType, Prover, Verifier,
};
use atlas_onnx_tracer::{model::trace::Trace, node::ComputationNode};
use common::consts::XLEN;
use joltworks::{
    field::JoltField,
    lookup_tables::unsigned_less_than::UnsignedLessThanTable,
    subprotocols::{
        shout::{self, RaOneHotEncoding},
        sumcheck::{BatchedSumcheck, SumcheckInstanceProof},
        sumcheck_prover::SumcheckInstanceProver,
        sumcheck_verifier::SumcheckInstanceVerifier,
    },
    transcripts::Transcript,
    utils::errors::ProofVerifyError,
};

/// Operator-specific hooks required by the shared neural teleport
/// range-check and one-hot proof flow.
pub trait NeuralTeleportRangeOneHot<F: JoltField, T: Transcript> {
    /// RA one-hot encoding descriptor used by `shout` sumcheck builders.
    type RaEncoding: RaOneHotEncoding;

    /// Produces lookup-table indices for each row in the current node trace.
    fn lookup_indices(&self, node: &ComputationNode, trace: &Trace) -> Vec<usize>;

    /// Builds the RA one-hot encoding descriptor for this node.
    ///
    /// Any node that is teleported involves a division, for which the remainder must be range-checked.
    /// This range-check is implemented using a one-hot encoding, which is proven using the `RaEncoding` descriptor.
    fn ra_encoding(&self, node: &ComputationNode) -> Self::RaEncoding;
}

/// Proves the shared stage that combines:
/// 1. teleport range-check RAF, and
/// 2. operator-specific RA one-hot checks,
///    then proves the range-check RA one-hot/hamming-weight consistency.
pub fn prove_range_and_onehot<F, T, NT>(
    node: &ComputationNode,
    prover: &mut Prover<F, T>,
    nt: &NT,
) -> Vec<(ProofId, SumcheckInstanceProof<F, T>)>
where
    F: JoltField,
    T: Transcript,
    NT: NeuralTeleportRangeOneHot<F, T>,
{
    let mut proofs = Vec::new();
    let lookup_indices = nt.lookup_indices(node, &prover.trace);
    let ra_encoding = nt.ra_encoding(node);

    let rangecheck_provider = RangeCheckProvider::<TeleportRangeCheckOperands>::new(node);
    let (rangecheck_sumcheck, rc_lookup_indices) = rangecheck_provider
        .read_raf_prove::<F, T, UnsignedLessThanTable<XLEN>>(
            &prover.trace,
            &mut prover.accumulator,
            &mut prover.transcript,
        );

    let ra_onehot_provers = shout::ra_onehot_provers(
        &ra_encoding,
        &lookup_indices,
        &prover.accumulator,
        &mut prover.transcript,
    );
    let mut range_and_ra_instances: Vec<Box<dyn SumcheckInstanceProver<F, T>>> =
        vec![Box::new(rangecheck_sumcheck)];
    range_and_ra_instances.extend(ra_onehot_provers);
    let (ra_one_hot_checks_proof, _) = BatchedSumcheck::prove(
        range_and_ra_instances
            .iter_mut()
            .map(|v| &mut **v as _)
            .collect(),
        &mut prover.accumulator,
        &mut prover.transcript,
    );
    proofs.push((
        ProofId(node.idx, ProofType::RaOneHotChecks),
        ra_one_hot_checks_proof,
    ));

    let rc_encoding = RangeCheckEncoding::<TeleportRangeCheckOperands>::new(node);
    let [rc_ra, rc_hw, rc_bool] = shout::ra_onehot_provers(
        &rc_encoding,
        &rc_lookup_indices,
        &prover.accumulator,
        &mut prover.transcript,
    );
    let mut instances: Vec<Box<dyn SumcheckInstanceProver<F, T>>> = vec![rc_ra, rc_hw, rc_bool];
    let (ra_hamming_weight_proof, _) = BatchedSumcheck::prove(
        instances.iter_mut().map(|v| &mut **v as _).collect(),
        &mut prover.accumulator,
        &mut prover.transcript,
    );
    proofs.push((
        ProofId(node.idx, ProofType::RaHammingWeight),
        ra_hamming_weight_proof,
    ));

    proofs
}

/// Verifies the shared stage that combines:
/// 1. teleport range-check RAF, and
/// 2. operator-specific RA one-hot checks,
///    plus the range-check RA one-hot/hamming-weight consistency proof.
pub fn verify_range_and_onehot<F, T, NT>(
    node: &ComputationNode,
    verifier: &mut Verifier<'_, F, T>,
    nt: &NT,
) -> Result<(), ProofVerifyError>
where
    F: JoltField,
    T: Transcript,
    NT: NeuralTeleportRangeOneHot<F, T>,
{
    let ra_one_hot_checks_proof = verifier
        .proofs
        .get(&ProofId(node.idx, ProofType::RaOneHotChecks))
        .ok_or(ProofVerifyError::MissingProof(node.idx))?;
    let ra_encoding = nt.ra_encoding(node);

    let rangecheck_provider = RangeCheckProvider::<TeleportRangeCheckOperands>::new(node);
    let rangecheck_verifier = rangecheck_provider
        .read_raf_verify::<F, T, UnsignedLessThanTable<XLEN>>(
            &mut verifier.accumulator,
            &mut verifier.transcript,
        );

    let ra_onehot_verifier = shout::ra_onehot_verifiers(
        &ra_encoding,
        &verifier.accumulator,
        &mut verifier.transcript,
    );
    let ra_onehot_verifier: Vec<&dyn SumcheckInstanceVerifier<F, T>> =
        ra_onehot_verifier.iter().map(|v| &**v as _).collect();
    let mut instances: Vec<&dyn SumcheckInstanceVerifier<F, T>> = vec![&rangecheck_verifier];
    instances.extend(ra_onehot_verifier);
    BatchedSumcheck::verify(
        ra_one_hot_checks_proof,
        instances,
        &mut verifier.accumulator,
        &mut verifier.transcript,
    )?;

    let ra_hamming_weight_proof = verifier
        .proofs
        .get(&ProofId(node.idx, ProofType::RaHammingWeight))
        .ok_or(ProofVerifyError::MissingProof(node.idx))?;

    let rc_encoding = RangeCheckEncoding::<TeleportRangeCheckOperands>::new(node);
    let [rc_ra, rc_hw, rc_bool] = shout::ra_onehot_verifiers(
        &rc_encoding,
        &verifier.accumulator,
        &mut verifier.transcript,
    );
    BatchedSumcheck::verify(
        ra_hamming_weight_proof,
        vec![&*rc_ra, &*rc_hw, &*rc_bool],
        &mut verifier.accumulator,
        &mut verifier.transcript,
    )?;

    Ok(())
}
