use crate::ops::round::ROUND_FRAC_BITS;

pub(crate) use crate::trace::build_layer_witness_from_trace_dir;

// Prover-side tensor material. The complete prover owns materialization; the
// IOP only borrows these views when proving individual equations.

#[derive(Debug, Clone)]
pub struct LayerWitness {
    pub hidden_in: Vec<i32>,
    pub rms_norm_atten_sum_x2: Vec<i64>,
    pub rms_norm_atten_norm_acc: Vec<i64>,
    pub rms_norm_atten_norm: Vec<i32>,
    pub rms_norm_atten_norm_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub rms_norm_atten_acc: Vec<i64>,
    pub rms_norm_atten_a: Vec<i32>,
    pub rms_norm_atten_b: Vec<i32>,
    pub rms_norm_atten_c: Vec<i32>,
    pub rms_norm_atten_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub context_acc: Vec<i64>,
    pub context: Vec<i32>,
    pub context_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub o_proj: Vec<i32>,
    pub o_proj_acc: Vec<i64>,
    pub o_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub softmax: Vec<i32>,
    pub softmax_acc: Vec<i64>,
    pub softmax_floor: Vec<i32>,
    pub softmax_floor_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub softmax_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub softmax_max_index: Vec<usize>,
    pub softmax_min_diff: i64,
    pub softmax_max_diff: i64,
    pub softmax_ra: Vec<u8>,
    pub softmax_exp_acc: Vec<i64>,
    pub softmax_exp_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub qk_score: Vec<i32>,
    pub qk_score_acc: Vec<i64>,
    pub qk_score_dot: Vec<i32>,
    pub qk_score_dot_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub qk_score_scale_acc: Vec<i64>,
    pub qk_score_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub q_rope_acc: Vec<i64>,
    pub q_rope: Vec<i32>,
    pub q_rope_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub k_rope_acc: Vec<i64>,
    pub k_rope: Vec<i32>,
    pub k_rope_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub q_proj: Vec<i32>,
    pub k_proj: Vec<i32>,
    pub q_norm_sum_x2: Vec<i64>,
    pub k_norm_sum_x2: Vec<i64>,
    pub q_norm_norm_acc: Vec<i64>,
    pub k_norm_norm_acc: Vec<i64>,
    pub q_norm_norm: Vec<i32>,
    pub k_norm_norm: Vec<i32>,
    pub q_norm_norm_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub k_norm_norm_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub q_norm_acc: Vec<i64>,
    pub k_norm_acc: Vec<i64>,
    pub q_norm: Vec<i32>,
    pub k_norm: Vec<i32>,
    pub q_norm_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub k_norm_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub q_proj_acc: Vec<i64>,
    pub q_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub k_proj_acc: Vec<i64>,
    pub k_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub v_proj_acc: Vec<i64>,
    pub v_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub softmax_max: Vec<i32>,
    pub softmax_exp: Vec<i32>,
    pub softmax_sum: Vec<i32>,
    pub v_proj: Vec<i32>,
    pub residual_add_attn_a: Vec<i32>,
    pub residual_add_attn_b: Vec<i32>,
    pub rms_norm_mlp_sum_x2: Vec<i64>,
    pub rms_norm_mlp_norm_acc: Vec<i64>,
    pub rms_norm_mlp_norm: Vec<i32>,
    pub rms_norm_mlp_norm_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub rms_norm_mlp_acc: Vec<i64>,
    pub rms_norm_mlp_a: Vec<i32>,
    pub rms_norm_mlp_b: Vec<i32>,
    pub rms_norm_mlp_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub gate_proj_acc: Vec<i64>,
    pub gate_proj: Vec<i32>,
    pub gate_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub silu_acc: Vec<i64>,
    pub silu: Vec<i32>,
    pub silu_min_n: i64,
    pub silu_max_n: i64,
    pub silu_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub silu_ra: Vec<u8>,
    pub silu_out_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub silu_up_acc: Vec<i64>,
    pub silu_up: Vec<i32>,
    pub silu_up_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub up_proj_acc: Vec<i64>,
    pub up_proj: Vec<i32>,
    pub up_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
    pub down_proj_acc: Vec<i64>,
    pub down_proj: Vec<i32>,
    pub down_proj_frac_bits: [Vec<u8>; ROUND_FRAC_BITS],
}
